a_x_multiplier: 4
a_y_multiplier: 2
agent_state_configs:
- [0, 1, 0, 0.0, 1.0, 0.0]
- [0, 2, 0, 0.0, 1.0, 0.0]
- [0, 3, 0, 0.0, 1.0, 0.0]
bid_ask_offset: 10000
exogenous_order_price_noise_mean: 0
exogenous_order_price_noise_std: 12000
external_market_fba_interval: 1
external_market_format: CDA
focal_market_fba_interval: 2
focal_market_format: CDA
fundamental_value_noise_mean: 0
fundamental_value_noise_std: 10000
fundamental_values:
- [1, 1000000]
- [5, 900000]
initial_price: 1000000
k_reference_price: 0.2
k_signed_volume: 0.5
lambdaI: [0.1, 0.1]
lambdaJ: 0.5
random_seed: 12338
read_fundamental_values_from_array: false
session_duration: 5
speed_unit_cost: 20000
tax_rate: 0.1
time_in_force: 7
