a_x_multiplier: 5
a_y_multiplier: 3
agent_state_configs:
- [0, 1, 0, 0, 0, 0]
- [0, 2, 0, 0, 0, 0]
- [0, 3, 0, 0, 0, 0]
bid_ask_offset: 20000
exogenous_order_price_noise_mean: 0
exogenous_order_price_noise_std: 30000
explore_all: true
explore_all_num_submoves: 6
external_market_fba_interval: 1
external_market_format: CDA
focal_market_fba_interval: 0.5
focal_market_format: FBA
fundamental_value_noise_mean: 0
fundamental_value_noise_std: 40000
fundamental_values:
- [0, 1000000]
init_y: 0.5
init_z: 0.5
initial_price: 1000000
k_reference_price: 0.2
k_signed_volume: 0.2
lambdaI: [0.1, 0.05]
lambdaJ: 2
move_interval: 10
num_moves: 8
random_seed: 12338
read_fundamental_values_from_array: false
session_duration: 10800
speed_unit_cost: 2000
step: 0.05
symmetric: false
tax_rate: 0.1
time_in_force: 1
