session_duration: 14400
initial_price: 1000000

fundamental_value_noise_mean: 0
fundamental_value_noise_std: 40000
read_fundamental_values_from_array: True

exogenous_order_price_noise_mean: 0
exogenous_order_price_noise_std: 30000
bid_ask_offset: 20000
time_in_force: 2

focal_market_format: CDA
external_market_format: CDA
focal_market_fba_interval: 1.5
external_market_fba_interval: 1

lambdaJ: .5
lambdaI: [0.1, 0.05]  # first element: focal market, second element: external market

tax_rate: 0.1
k_reference_price: 0.2 # discount rate (half life)
k_signed_volume: 0.2

a_x_multiplier: 5   # a_x <-> signed volume
a_y_multiplier: 10   # a_y <-> inventory

speed_unit_cost: 2000  # per second

random_seed: 12338

fundamental_values:
  #  time, fundamental value
  - [0,    1000000]

agent_state_configs:
  #  arrival_time, agent_num, speed, a_x, a_y, w
  - [0,            1,         0,     0,   0, 0]
  - [0,            2,         0,     0,   0, 0]
  - [0,            3,         0,     0,   0, 0]
