a_x_multiplier: 5
a_y_multiplier: 3
agent_state_configs:
- [0, 1, 0, 0, 0, 0]
- [0, 2, 0, 0, 0.25, 0.25]
- [0, 3, 0, 0, 0.25, 0.25]
- [0, 4, 0, 0, 0.25, 0.25]
- [0, 5, 0, 0, 0.25, 0.75]
- [0, 6, 0, 0, 0.25, 0.75]
bid_ask_offset: 20000
exogenous_order_price_noise_mean: 0
exogenous_order_price_noise_std: 30000
explore_all: false
explore_all_num_submoves: 7
external_market_fba_interval: 1
external_market_format: CDA
focal_market_fba_interval: 0.1
focal_market_format: CDA
fundamental_value_noise_mean: 0
fundamental_value_noise_std: 40000
fundamental_values:
- [0, 1000000]
grid_search: true
grid_search_symmetric: false
iex_delay: 0.035
init_speed: false
init_y: false
init_z: false
initial_price: 1000000
k_reference_price: 0.2
k_signed_volume: 0.2
lambdaI: [0.1, 0.07]
lambdaJ: 0.5
move_interval: 10
num_moves: 51
num_repeats: 10
peg_proportion: 0.5
random_seed: false
read_fundamental_values_from_array: false
session_duration: 10200
speed_unit_cost: 500
speeds: [0, 1]
step: 0.05
symmetric: false
tax_rate: 0.1
time_in_force: 5
ys: [0, 0.25, 0.5, 0.75, 1]
zs: [0, 0.25, 0.5, 0.75, 1]
